name: AnchorFix
version: '${project.version}'
api-version: 1.7.10
main: me.fadingfog.anchorfix.AnchorFix
description: RailCraft anchor chunk loading fix
website: https://github.com/FadingFog/
authors: [FadingFog]
commands:
  anchorfix:
    description: Extra commands to control this plugin
    usage: |
           /<command> clean - remove missing in the world anchors from the config
           /<command> remove - remove all npc created by this plugin
           /<command> check <player> [-i] - get a list of player anchors; -i for detailed info
    permission: anchorfix
permissions:
  anchorfix:
    description: Allows to use anchorfix commands
    default: op